INSERT INTO TB_USUARIO (username, password)
VALUES ('GuiJanuario', '$2a$10$v2mOdFrM4NVBj/JM68s29OhuFHbiC7rnbm9assASaW4Ja7CC7e/Bu');


INSERT INTO TB_ROLE (role) VALUES ('ROLE_USER');
INSERT INTO TB_ROLE (role) VALUES ('ROLE_ADMIN');

INSERT INTO TB_USUARIOS_ROLES (id_usuario, id_role)
VALUES (1, (SELECT 2 FROM TB_ROLE WHERE role = 'ROLE_ADMIN'));

SELECT * FROM TB_ROLE;
SELECT * FROM TB_USUARIO;
SELECT * FROM TB_USUARIOS_ROLES;

